services:
  drupal:
    image: drupal:9.5.11-php8.2-apache
    container_name: drupal-container
    ports:
      - 8080:80
    volumes:
      - drupal-data:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14.13
    container_name: postgres-container
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=drupal
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  drupal-data:
  db-data: